name: Main workflow

on:
  push:
    paths:
      - .github/**

env:
  NODE_VERSION: '14' 

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Upload Dockerfile
        uses: actions/upload-artifact@v2
        with:
          name: dockerfile
          path: Dockerfile
      - name: Checkout Nodejam repo
        uses: actions/checkout@v2
        with:
          repository: komarserjio/notejam
      - name: Upload Express NoteJam app
        uses: actions/upload-artifact@v2
        with:
          name: express-notejam-app
          path: express/notejam

  test_and_build:
    runs-on: ubuntu-latest
    needs: [checkout]
    env:
      APP_FOLDER: ${{ github.workspace }}/app
    steps:
      - name: Download Express NoteJam app
        uses: actions/download-artifact@v2
        with:
          name: express-notejam-app
          path: ${{ env.APP_FOLDER }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: cd ${{ env.APP_FOLDER }} && npm install
      - name: Test application
        run: cd ${{ env.APP_FOLDER }} && ./node_modules/mocha/bin/mocha tests
      - name: Init database
        run: cd ${{ env.APP_FOLDER }} && node db.js
      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: dockerfile
      - name: Login to Docker registry
        uses: Azure/docker-login@v1
        with:
          login-server: notepadacr.azurecr.io
          username: ${{ secrets.ACR_SPA_ID }}
          password: ${{ secrets.ACR_SPA_PASSWORD }}
      - name: Build Docker image
        run: docker build -t notepadacr.azurecr.io/notepadapp:${{ github.sha }} .
      - name: Push Docker image
        run: docker push notepadacr.azurecr.io/notepadapp:${{ github.sha }}
